### ISSUE TITLE
Sorry for New Branch and Pull Request

### ISSUE THREAD

**Issue by Leedabord** [ionicthemes/ionic-firebase-starter-app#10]
Hello @djabif,

Sorry for creating a new invalid pull request as a "noob" on github, ionic and firebase.  I was trying to get this to work on stackblitz and deploy to firebase but have run into multiple issues with ionic 4, 5  and angular 8,9  on stackblitz.  

I will try to "import" the repository to a new one instead of creating a "fork" so as to avoid remaining linked to your repository.

Cheers

**Comment by djabif** [comment]
No prob! There's always a first time for all of us. Happy coding 😁
